name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção da iamgem e push docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            yanpaiva/fake-shop:latest
            yanpaiva/fake-shop:v${{ github.run_number }}
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Configurar o kubectl
        run: aws eks upudate-kubeconfig --name aula-k8s
      - name: Aplicar os maniestos no kubernetes
        run: echo "Executando o comando kubectl apply"


        
