name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar no Docker Hub
        run: echo "Executando o comando Docker Login"
      - name: Construção da Imagem Docker
        run: echo "Executando o comando dockere build"
      - name: Envio da Imagem Docker
        run: echo "Executando o comando dockere push"
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o comando AWS configure"
      - name: Configurar o kubectl
        run: echo "Executando o comando AWS eks update-kubeconfig"
      - name: Aplicar os maniestos no kubernetes
        run: echo "Executando o comando kubectl apply"


        
